// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.Data;

#nullable disable

namespace aspnetserver.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("aspnetserver.Data.Sweater", b =>
                {
                    b.Property<int>("SweaterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("SweaterId");

                    b.ToTable("Sweaters");

                    b.HasData(
                        new
                        {
                            SweaterId = 1,
                            manufacturer = "Sweater 1",
                            quantity = 1
                        },
                        new
                        {
                            SweaterId = 2,
                            manufacturer = "Sweater 2",
                            quantity = 2
                        },
                        new
                        {
                            SweaterId = 3,
                            manufacturer = "Sweater 3",
                            quantity = 3
                        },
                        new
                        {
                            SweaterId = 4,
                            manufacturer = "Sweater 4",
                            quantity = 4
                        },
                        new
                        {
                            SweaterId = 5,
                            manufacturer = "Sweater 5",
                            quantity = 5
                        },
                        new
                        {
                            SweaterId = 6,
                            manufacturer = "Sweater 6",
                            quantity = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
