const API_BASE_URL_DEVELOPMENT = "https://localhost:7002";
const API_BASE_URL_PRODUCTION =
  "https://sweatercrudapp-aspnetserver.azurewebsites.net";

const ENDPOINTS = {
  GET_ALL_SWEATERS: "get-all-sweaters",
  GET_SWEATERS_BY_ID: "get-sweater-by-id",
  CREATE_SWEATER: "create-sweater",
  UPDATE_SWEATER: "update-sweater",
  DELETE_SWEATER_BY_ID: "delete-sweater-by-id",
};

const development = {
  API_URL_GET_ALL_SWEATERS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_SWEATERS}`,
  API_URL_GET_SWEATERS_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_SWEATERS_BY_ID}`,
  API_URL_CREATE_SWEATER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_SWEATER}`,
  API_URL_UPDATE_SWEATER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_SWEATER}`,
  API_URL_DELETE_SWEATER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_SWEATER_BY_ID}`,
};

const production = {
  API_URL_GET_ALL_SWEATERS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_SWEATERS}`,
  API_URL_GET_SWEATERS_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_SWEATERS_BY_ID}`,
  API_URL_CREATE_SWEATER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_SWEATER}`,
  API_URL_UPDATE_SWEATER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_SWEATER}`,
  API_URL_DELETE_SWEATER_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_SWEATER_BY_ID}`,
};

const Constants =
  process.env.NODE_ENV === "development" ? development : production;

export default Constants;
